include:
  - package:flutter_lints/flutter.yaml
  - package:very_good_analysis/analysis_options.yaml

analyzer:
  errors:
    specify_nonobvious_property_types: ignore
  exclude:
    - "**/*.gql.dart"
    - "**/*.gql.g.dart"
    - "test/drift/**.dart"

linter:
  rules:
    directives_ordering: false
    sort_pub_dependencies: false
    public_member_api_docs: false
    sort_constructors_first: false
    require_trailing_commas: false
    always_use_package_imports: false
    lines_longer_than_80_chars: false
    avoid_catches_without_on_clauses: false
    avoid_positional_boolean_parameters: false

bloc:
  rules:
    - avoid_public_fields
    - avoid_flutter_imports
    - avoid_public_bloc_methods
    - prefer_void_public_cubit_methods
