include:
  - package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - "lib/api/grpc/**"
    - "packages/**"
    - "temp/**"

linter:
  rules:
    directives_ordering: false
    sort_pub_dependencies: false
    public_member_api_docs: false
    always_use_package_imports: false
    lines_longer_than_80_chars: false
