{
  "sksl": {
    "entrypoint": "blurhash_64_fragment_main",
    "shader": "// This SkSL shader is autogenerated by spirv-cross.\n\nfloat4 flutter_FragCoord;\n\nuniform vec2 startPos;\nuniform vec2 iResolution;\nuniform vec2 num;\nuniform vec4 colors[64];\n\nvec4 fragColor;\n\nvec2 FLT_flutter_local_FlutterFragCoord()\n{\n    return flutter_FragCoord.xy;\n}\n\nfloat FLT_flutter_local_linearTosRGB(float value)\n{\n    float v = max(0.0, min(1.0, value));\n    if (v <= 0.003130800090730190277099609375)\n    {\n        return v * 12.9200000762939453125;\n    }\n    else\n    {\n        return (pow(v, 0.4166666567325592041015625) * 1.05499994754791259765625) - 0.054999999701976776123046875;\n    }\n}\n\nvoid FLT_main()\n{\n    vec2 fragCoord = FLT_flutter_local_FlutterFragCoord();\n    vec2 uv = (fragCoord - startPos) / iResolution;\n    vec3 color = vec3(0.0);\n    vec2 uvpi = uv * 3.1415927410125732421875;\n    float size = num.x * num.y;\n    for (int index = 0; index < 64; index++)\n    {\n        if (float(index) >= size)\n        {\n            break;\n        }\n        vec3 sColor = colors[index].xyz;\n        float fIndex = float(index);\n        float row = floor(fIndex / num.x);\n        float col = floor(fIndex - (row * num.x));\n        vec2 loopPos = vec2(col, row);\n        vec2 basics = uvpi * loopPos;\n        color += ((sColor * cos(basics.x)) * cos(basics.y));\n    }\n    float param = color.x;\n    float param_1 = color.y;\n    float param_2 = color.z;\n    fragColor = vec4(FLT_flutter_local_linearTosRGB(param), FLT_flutter_local_linearTosRGB(param_1), FLT_flutter_local_linearTosRGB(param_2), 1.0);\n}\n\nhalf4 main(float2 iFragCoord)\n{\n      flutter_FragCoord = float4(iFragCoord, 0, 0);\n      FLT_main();\n      return fragColor;\n}\n",
    "stage": 1,
    "uniforms": [
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 0,
        "name": "startPos",
        "rows": 2,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 1,
        "name": "iResolution",
        "rows": 2,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 2,
        "name": "num",
        "rows": 2,
        "type": 10
      },
      {
        "array_elements": 64,
        "bit_width": 32,
        "columns": 1,
        "location": 3,
        "name": "colors",
        "rows": 4,
        "type": 10
      }
    ]
  }
}