include:
  - package:very_good_analysis/analysis_options.yaml

analyzer:
  errors:
    specify_nonobvious_property_types: ignore
  exclude:
    - "**/*.g.dart"
    - "**/*.gr.dart"
    - "**/*.schema.dart"
    - "**/*.freezed.dart"
    - "lib/jaspr_options.dart"

linter:
  rules:
    avoid_print: false
    directives_ordering: false
    sort_pub_dependencies: false
    public_member_api_docs: false
    require_trailing_commas: false
    sort_constructors_first: false
    always_use_package_imports: false
    lines_longer_than_80_chars: false
    avoid_catches_without_on_clauses: false
